---
- name: Konfigurer Cisco-router
  hosts: router1
  gather_facts: no
  vars_files:
    - vars_router.yaml

  tasks:
    - name: Sett hostname
      ios_config:
        config:
          - hostname "{{ hostname }}"
      # Setter vertens navn (hostname) på routeren

    - name: Konfigurer VLAN database
      ios_config:
        config:
          - vlan {{ item.vlan }}  # Definer VLAN
          - name {{ item.name }}  # Tildeler et navn til VLAN (valgfritt, men nyttig for administrasjon)
      loop: "{{ interfaces }}"
      when: item.vlan is defined
      register: vlan_db_result
      # Konfigurer VLAN i VLAN-databasen

    - name: Konfigurer IP-adresser på grensesnitt
      ios_config:
        config:
          - interface {{ item.name }}
          - ip address {{ item.ip }} {{ item.mask }}
          - no shutdown  # Sørg for at grensesnittet ikke er administrativt nedstengt
      loop: "{{ interfaces }}"
      when: item.ip is defined and item.mask is defined
      register: interface_result
      # Konfigurer IP-adresser på de spesifiserte grensesnittene

    - name: Konfigurer VLAN på grensesnitt
      ios_config:
        config:
          - interface {{ item.name }}
          - encapsulation dot1Q {{ item.vlan }}  # Brukes bare hvis VLAN er definert
      loop: "{{ interfaces }}"
      when: item.vlan is defined
      register: vlan_result
      # Konfigurer VLAN på grensesnittet med dot1Q-kapsling

    - name: Legg til statiske ruter
      ios_config:
        config:
          - ip route {{ item.dest }} {{ item.mask }} {{ item.next_hop }}
      loop: "{{ static_routes }}"
      # Legg til statiske ruter for trafikdirigering

    - name: Konfigurer OSPF
      ios_config:
        config:
          - router ospf {{ ospf.process_id }}
          - network {{ item.network }} {{ item.wildcard }} area {{ item.area }}
      loop: "{{ ospf.networks }}"
      # Konfigurer OSPF for ruting

    - name: Aktiver DHCP-tjeneste
      ios_config:
        config:
          - service dhcp
      when: dhcp.enabled
      # Aktiverer DHCP-serveren hvis den er aktivert i variablene

    - name: Konfigurer DHCP
      ios_config:
        lines:
          - network {{ dhcp.network }} {{ dhcp.netmask }}
          - default-router {{ dhcp.default_router }}
          - dns-server {{ dhcp.dns_servers }}
          - lease {{ dhcp.lease_time }}
        parents: "ip dhcp pool {{ dhcp.pool_name }}"
      when: dhcp.enabled
      # Konfigurer DHCP-serverinnstillinger som nettverk, standard-gateway, DNS-servere og lease-tid

    - name: Konfigurer HSRP
      ios_config:
        config:
          - interface {{ item.interface }}
          - standby {{ item.group }} ip {{ item.virtual_ip }}
          - standby {{ item.group }} priority {{ item.priority }}
          - standby {{ item.group }} preempt
      loop: "{{ hsrp }}"
      # Konfigurer HSRP for redundant gateway-konfigurasjon

    - name: Lagre kjørende konfigurasjon
      ios_command:
        commands:
          - write memory
      # Lagre den kjørende konfigurasjonen til minnet på routeren

    # Verifiser IP-konfigurasjon på grensesnitt
    - name: Verifiser IP-konfigurasjon på grensesnitt
      ios_command:
        commands:
          - show ip interface brief
      register: interface_ip_output
      # Kjør kommandoen for å vise IP-konfigurasjonen

    - name: Vis IP-konfigurasjon på grensesnitt
      debug:
        msg: "{{ interface_ip_output.stdout }}"
      # Vis IP-konfigurasjonen på grensesnittene i debug-kommandoen

    # Verifiser status på grensesnittene
    - name: Verifiser status på grensesnitt
      ios_command:
        commands:
          - show interfaces status
      register: interface_status_output
      # Kjør kommandoen for å vise status på grensesnittene

    - name: Vis status på grensesnitt
      debug:
        msg: "{{ interface_status_output.stdout }}"
      # Vis statusen på grensesnittene i debug-kommandoen

    # Verifiser VLAN-konfigurasjon
    - name: Verifiser VLAN-konfigurasjon
      ios_command:
        commands:
          - show running-config | include vlan
      register: vlan_output
      # Kjør kommandoen for å vise VLAN-konfigurasjonen

    - name: Vis VLAN-konfigurasjon
      debug:
        msg: "{{ vlan_output.stdout }}"
      # Vis VLAN-konfigurasjonen i debug-kommandoen

    # Verifiser OSPF-konfigurasjon
    - name: Verifiser OSPF-konfigurasjon
      ios_command:
        commands:
          - show ip ospf neighbor
      register: ospf_output
      # Kjør kommandoen for å vise OSPF-naboer

    - name: Vis OSPF-nabo
      debug:
        msg: "{{ ospf_output.stdout }}"
      # Vis OSPF-naboer i debug-kommandoen
