- name: Konfigurer Cisco-switcher
  hosts: cisco_switches
  gather_facts: no
  vars_files:
    - vars_switch.yaml
  connection: network_cli
  become: yes
  become_method: enable

  tasks:
    - name: Sett hostname
      cisco.ios.ios_config:
        lines:
          - "hostname {{ hostname }}"
        save_when: modified
      # Setter vertens navn (hostname) p책 switchen

    - name: Konfigurer VLAN
      cisco.ios.ios_config:
        lines:
          - "vlan {{ item.id }}"
          - "name {{ item.name }}"
      loop: "{{ vlans }}"
      register: vlan_result
      notify: Save config
      # Konfigurer VLAN p책 switchen, tildeler ID og navn for hvert VLAN

    - name: Konfigurer trunk-porter
      cisco.ios.ios_config:
        parents: "interface {{ item }}"
        lines:
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 10,20"
          - "no shutdown"
      loop: "{{ trunk_ports }}"
      register: trunk_result
      notify: Save config
      vars:
        ansible_command_timeout: 60
      # Konfigurer trunk-porter, tillater VLAN 10 og 20 og aktiverer portene

    - name: Konfigurer access-porter
      cisco.ios.ios_config:
        parents: "interface {{ item.port }}"
        lines:
          - "switchport mode access"
          - "switchport access vlan {{ item.vlan }}"
          - "no shutdown"
      loop: "{{ access_ports }}"
      register: access_result
      notify: Save config
      # Konfigurer access-porter, tilknyt VLAN til portene og aktiver portene

    - name: Konfigurer EtherChannel
      block:
        - name: Konfigurer fysiske porter
          cisco.ios.ios_config:
            parents: "interface {{ item }}"
            lines:
              - "channel-group {{ etherchannel.group }} mode {{ etherchannel.mode }}"
              - "no shutdown"
          loop: "{{ etherchannel.ports }}"
          register: etherchannel_ports
          # Konfigurer fysiske porter som en del av EtherChannel-gruppen

        - name: Konfigurer Port-channel-grensesnitt
          cisco.ios.ios_config:
            parents: "interface Port-channel{{ etherchannel.group }}"
            lines:
              - "switchport mode trunk"
              - "switchport trunk allowed vlan 10,20"
              - "no shutdown"
          register: portchannel_result
          # Konfigurer EtherChannel som trunk og tillater VLAN 10 og 20 p책 port-channel-grensesnittet

      rescue:
        - name: Vis EtherChannel-feil
          debug:
            msg: "Failed to configure EtherChannel. Check switch logs."
          # Hvis EtherChannel-konfigurasjonen mislykkes, vis feilmelding

      always:
        - name: Verifiser EtherChannel
          cisco.ios.ios_command:
            commands: "show etherchannel summary"
          register: etherchannel_verify
          changed_when: false
          # Verifiser EtherChannel-konfigurasjonen ved 책 vise oppsummeringen

    - name: Konfigurer VRF (betinget)
      block:
        - name: Opprett VRF-definisjon
          cisco.ios.ios_config:
            lines: "vrf definition {{ vrf.name }}"
            parents: []
          when: vrf.name != ""
          register: vrf_create
          # Opprett VRF-definisjonen hvis vrf.name er spesifisert

        - name: Konfigurer adressefamilie
          cisco.ios.ios_config:
            lines:
              - "address-family ipv4"
              - "exit-address-family"
            parents: "vrf definition {{ vrf.name }}"
          when: vrf.name != ""
          register: vrf_def_result
          notify: Save config
          # Konfigurer adressefamilien for VRF (IPv4)

      rescue:
        - name: Vis VRF-konfigurasjonsfeil
          debug:
            msg: "Failed to configure VRF. Check switch logs."
          # Hvis VRF-konfigurasjonen mislykkes, vis feilmelding

    - name: Tilordne interfaces til VRF (betinget)
      cisco.ios.ios_config:
        parents: "interface {{ item }}"
        lines: "vrf forwarding {{ vrf.name }}"
      loop: "{{ vrf.interfaces }}"
      when: vrf.name != "" and item != ""
      register: vrf_intf_result
      notify: Save config
      # Tilordne interfaces til VRF hvis VRF-navn er spesifisert

  handlers:
    - name: Save config
      cisco.ios.ios_config:
        save_when: modified
      when: >
        vlan_result is changed or
        trunk_result is changed or
        access_result is changed or
        etherchannel_ports is changed or
        portchannel_result is changed or
        vrf_def_result is changed or
        vrf_intf_result is changed
      # Lagre konfigurasjonen hvis det har skjedd endringer i VLAN, trunk, access, EtherChannel, eller VRF
