# Vars for router
hostname: "Router1"

# Grensesnitt-konfigurasjon (med VLAN)
interfaces:
  - { name: "GigabitEthernet0/0", ip: "192.168.5.1", mask: "255.255.255.0", vlan: 10 }
  - { name: "GigabitEthernet0/1", ip: "192.168.1.1", mask: "255.255.255.0", vlan: 20 }

# Statisk ruter
static_routes:
  - { dest: "0.0.0.0", mask: "0.0.0.0", next_hop: "192.168.2.254" }

# OSPF-konfigurasjon
ospf:
  process_id: 1
  networks:
    - { network: "192.168.1.0", wildcard: "0.0.0.255", area: 0 }
    - { network: "192.168.2.0", wildcard: "0.0.0.255", area: 0 }

# DHCP-konfigurasjon
dhcp:
  enabled: true
  pool_name: "Router2_pool"
  network: "192.168.1.0"
  netmask: "255.255.255.0"
  default_router: "192.168.1.1"
  dns_servers: "8.8.8.8"
  lease_time: "12"

# HSRP-konfigurasjon
hsrp:
  - { interface: "GigabitEthernet0/0", group: 1, virtual_ip: "192.168.2.254", priority: 110, preempt: true }
  - { interface: "GigabitEthernet0/1", group: 1, virtual_ip: "192.168.1.254", priority: 110, preempt: true }
